[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "schedium"
dynamic = ["version"]
requires-python = ">=3.10"
maintainers = [
  {name = "Marc Bresson", email = "m.bresson@mailo.eu"},
]
description = "Automatically trigger jobs at specific times"
readme = "README.md"
keywords = ["scheduling"]
classifiers=[
  "Development Status :: 4 - Beta",
  "Intended Audience :: Developers",
  "Intended Audience :: Science/Research",
  "License :: OSI Approved :: Apache Software License",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "Topic :: Software Development",
  "Topic :: Scientific/Engineering",
  "Typing :: Typed",
]

[project.urls]
Repository = "https://github.com/MarcBresson"
Issues = "https://github.com/MarcBresson"
Changelog = "https://github.com/MarcBresson"

[dependency-groups]
dev = [
    "mypy",
    "pre-commit",
    "ipykernel",
    "ipython",
]
docs = [
  "sphinx>=7",
  "furo>=2025.12.19",
  "numpydoc>=1.10.0",
  "sphinx_copybutton>=0.5.2",
  "sphinxext-opengraph[social_cards]>=0.13.0",
]
test = [
  "pytest",
  "pytest-cov",
  "pytest-mock",
]

[tool.setuptools.dynamic]
version = {attr = "schedium.__version__"}

[tool.pytest.ini_options]
pythonpath = ["."]

[tool.numpydoc_validation]
checks = [
    "GL01",
    "GL02",
    "GL03",
    "GL05",
    "GL06",
    "GL07",
    "GL09",
    "GL10",
    "SS01",
    "SS02",
    "SS03",
    "SS04",
    "SS05",
    "SS06",
    "PR01",
    "PR02",
    "PR03",
    "PR04",
    "PR05",
    "PR06",
    "PR07",
    "PR08",
    "PR09",
    "PR10",
    "RT02",
    "RT03",
    "RT04",
    "RT05",
    "SA02",
    "SA03",
    "SA04",
]

exclude_files = [ # don't process filepaths that match these regex
    '^tests/.*',
]
